textIn = 'ATCGATGCATGCATCGATGCA'
patternIn = 'ATC'


def patternCount(text, pattern):
    count = 0
    patternlen = len(pattern)
    textlen = len(text)

    for i in range(0, textlen):
        patternInText = text[i:i + patternlen]  # slide window for text
        if text[i:i + patternlen] == pattern:
            count += 1

    return count  # Number of times pattern is in text


def frequentWords(text, k):  # finds most frequent k-mers
    frequentPatterns = []
    pattern = ''
    count = []
    for i in range(0, len(text) - k):
        pattern = text[i:i + k]
        count.append(patternCount(text, pattern))

    maxcount = max(count)  # more to do here
    for i in range(0, len(text) - k):
        if count[i] == maxcount:
            frequentPatterns.append(text[i:i + k])
            print(text[i:i + k])

    return set(frequentPatterns)


myresult = frequentWords(textIn, 3)
print(myresult)
# print(__name__)

text_in_homework = 'GCCCTTCCCAGTACGTGGCCCTTCTACGTCGGCCCTTCTTATAAGCCCTTCGCCCTTCAGCCCTTCGCCCTTCATGCCCTTCGGCCCTTCAGCCCTTCGTCGCCCTTCGCCCTTCGCCCTTCGGCCCTTCCGCCCTTCGCCCTTCGCCCTTCAGCCCTTCGCCCTTCTCGGCCCTTCGCCCTTCGCGGCCCTTCATGCCCTTCCTTAGGGCCCTTCGTGCCCTTCGGGCCCTTCGCCCTTCCAGCCCTTCGCTCTATGCCCTTCGCGCCCTTCTACTGATGCCCTTCTGCCCTTCAGCCCTTCCTAGCCCTTCGCCCTTCGTCTGGCCCTTCAGCCCTTCCTGCGCCCTTCAATACTGCACAGATTGGCGCCCTTCGCTTTCGGTCTGCCCTTCTAGGCCCTTCGCCCTTCATGTGGCCCTTCGCCCTTCGCCCTTCGCAGGGCCCTTCGTCGCCCTTCTCGGCCCTTCGTCGCCCTTCGGAGCCCTTCGCCCTTCTTGCCCTTCCGCCCTTCACTGCCCTTCTACCGAAGAAGCCCTTCGGCCCTTCGCCCTTCGCGTCCAGCCCTTCGAGCCCTTCTAGCCCTTCAAAGCCCTTCGCCCTTCGGCGCATACGCGTTGTCTCGCCCTTCTAGAGAGCCCTTCGCCCTTCAATCAACCGCCCTTCGAGCGTACCCGTCCGTAGGGCTGCCCTTCGAGCCCTTCCGCCCTTCACGCCCTTCGGCCCTTCCTGGCCCTTCTCTAGCCCTTCATTCAGTGCCCTTCTGAACGCCCTTCAGGGAGCCCTTCTGCCCTTCAGTAGCCCTTCCCCGTTCGCCCTTCGTCAAATCTGGGCCCTTCTCGGTGGCCCTTCGCCCTTCGCCCTTCCGCCCTTCAGCCCTTCGGGATACGCCCTTCAATGTTGCCCTTCTGCCCTTCCATGAGTGGGCCCTTCAGCCCTTCAGCCCTTCGATCAGGGCCCTTCCGCCCTTCGCCCTTCAAAGCCCTTCTACGAAGCCCTTCCGCCCTTCCACCAACGCCCTTCGCCCTTCAATGCCCCTGCCCTTCGCCCTTCA'
pattern_in_homework = 'GCCCTTCGC'

print('result is: ' + str(patternCount(text_in_homework,pattern_in_homework)))


